server:
  port: 8080
spring:
  application:
    name: management-service
  datasource:
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://${DB_URL}:5432/postgres?autoreconnect=true&createDatabaseIfNotExist=true
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
    show-sql: false
  flyway:
    url: jdbc:postgresql://${DB_URL}:5432/postgres
    schemas: ms
    user: ${DB_USERNAME}
    password: ${DB_PASSWORD}