server:
  port: 8080
spring:
  config:
    import: optional:secrets.yml
  application:
    name: management-service
  datasource:
    password: root
    url: jdbc:postgresql://localhost:5432/postgres?autoreconnect=true&createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        format_sql: false
    show-sql: false
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    schemas: ms
    user: root
    password: root
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
    version: openapi_3_0
  swagger-ui:
    path: /swagger-ui.html
ms:
  aws:
    accessKey:
    secretKey:
    region:
    cognito:
      userPoolId: