name: CD
on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed
    branches:
      - 'master'
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Publish to ECR
    runs-on: ubuntu-latest

    steps:
      # Required to run ./gradlew permissions maybe?
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build with Gradle
        run: ./gradlew -Pcd -DAWS_ECR_IMAGE_ID=${{ secrets.AWS_ECR_IMAGE_ID }} -DAWS_ECR_URL=${{ secrets.AWS_ECR_URL }} clean jib -x test